const K={shows:'mytv-v5-shows',watched:'mytv-v5-watched',services:'mytv-v5-services',prefs:'mytv-v5-prefs'};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let shows=load(K.shows,[]),watched=load(K.watched,{}),services=load(K.services,[]),prefs=load(K.prefs,{}),route='home';const V=$('#view');
const nav=[['home','⌂','Home'],['calendar','▦','My Calendar'],['shows','♥','My Shows'],['discover','⌕','Discover'],['more','•••','More']];$('#mobileNav').innerHTML=nav.map(x=>'<button data-go="'+x[0]+'"><b>'+x[1]+'</b><span>'+x[2]+'</span></button>').join('');$('#side').innerHTML=[...nav.slice(0,4),['catchup','✓','Catch Up'],['night','★','Build My Night'],['services','▶','Streaming Services'],['account','♟','Account'],['alerts','✉','Email Alerts'],['settings','⚙','Settings']].map(x=>'<button data-go="'+x[0]+'">'+x[2]+'</button>').join('');document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});
function go(r){route=r;document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===r));({home,calendar,myshows,discover,more,catchup,night,services:servicePage,account,alerts,settings}[r]||home)();scrollTo(0,0)}
function mdY(d){if(!d)return'';let m=String(d).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?Number(m[2])+'/'+Number(m[3])+'/'+m[1]:d}function dayDiff(d){if(!d)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(d+'T00:00:00');return Math.round((b-a)/86400000)}function label(d){let n=dayDiff(d);if(n===null)return'Upcoming';if(n<0)return'Aired';if(n===0)return'Tonight';return new Date(d+'T00:00:00').toLocaleDateString('en-US',{weekday:'long'})}
function homeCard(x){return '<div class="card"><div class="showrow">'+(x.image?'<img class="poster" src="'+esc(x.image)+'">':'<div></div>')+'<div><div class="title">'+esc(x.name)+'</div><div class="sub">'+esc(x.network||x.status||'')+'</div><span class="pill">'+esc(label(x.airdate))+'</span></div><div class="actions single"><button class="btn" onclick="details('+Number(x.id)+')">Details</button></div></div></div>'}
function myShowCard(x){return '<div class="card"><div class="showrow">'+(x.image?'<img class="poster" src="'+esc(x.image)+'">':'<div></div>')+'<div><div class="title">'+esc(x.name)+'</div><div class="sub">'+esc(x.network||x.status||'')+'</div><span class="pill">'+esc(label(x.airdate))+'</span></div><div class="actions"><button class="btn" onclick="details('+Number(x.id)+')">Details</button><button class="btn danger" onclick="unfollow('+Number(x.id)+')">Unfollow</button></div></div></div>'}
function home(){V.innerHTML='<h1>Good '+(new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening')+' 👋</h1><div class="sub">Here’s what’s coming up across your streaming services.</div><div class="fresh">● Live data ready</div><div class="stats"><div class="stat"><b>'+shows.length+'</b>Shows followed</div><div class="stat"><b>'+services.length+'</b>Services</div><div class="stat"><b>'+shows.filter(x=>dayDiff(x.airdate)<=0).length+'</b>Ready to watch</div></div><h2>Tonight & Coming Up</h2>'+(shows.length?shows.map(homeCard).join(''):'<div class="empty">Follow shows from Discover and they will appear here.</div>')}
function calendar(){const groups=[['Today',x=>dayDiff(x.airdate)===0],['Tomorrow',x=>dayDiff(x.airdate)===1],['This Week',x=>{let n=dayDiff(x.airdate);return n>=2&&n<=7}],['Later',x=>dayDiff(x.airdate)>7||dayDiff(x.airdate)===null]];V.innerHTML='<h2>My Calendar</h2>'+groups.map(g=>{let a=shows.filter(g[1]);return '<section><h3>'+g[0]+'</h3>'+(a.length?a.map(homeCard).join(''):'<div class="empty">Nothing scheduled.</div>')+'</section>'}).join('')}
function myshows(){V.innerHTML='<h2>My Shows</h2><div class="sub" style="margin-bottom:16px">'+shows.length+' followed</div>'+(shows.length?shows.map(myShowCard).join(''):'<div class="empty">Your followed shows will appear here.</div>')}
async function discover(){V.innerHTML='<h2>Discover</h2><div class="sub">Search live TV data and follow shows.</div><input id="q" class="search" placeholder="Search shows"><button class="btn" onclick="searchShows()">Search</button><div id="results" style="margin-top:14px"></div>'}
async function searchShows(){let q=$('#q').value.trim(),R=$('#results');if(!q)return;R.innerHTML='<div class="sub">Searching…</div>';try{let d=await fetch('https://api.tvmaze.com/search/shows?q='+encodeURIComponent(q)).then(r=>r.json());R.innerHTML=d.slice(0,12).map(z=>{let x=z.show,on=shows.some(y=>Number(y.id)===Number(x.id));return '<div class="card"><div class="showrow">'+(x.image?.medium?'<img class="poster" src="'+esc(x.image.medium)+'">':'<div></div>')+'<div><div class="title">'+esc(x.name)+'</div><div class="sub">'+esc(x.network?.name||x.webChannel?.name||x.status||'')+'</div></div><div class="actions single">'+(on?'<button class="btn" disabled>Following</button>':'<button class="btn" onclick="follow('+Number(x.id)+')">Save + Follow</button>')+'</div></div></div>'}).join('')||'<div class="empty">No results.</div>'}catch{R.innerHTML='<div class="empty">Search is unavailable right now.</div>'}}
async function follow(id){let x=await fetch('https://api.tvmaze.com/shows/'+id+'?embed=nextepisode').then(r=>r.json());let e=x._embedded?.nextepisode||{};if(!shows.some(y=>Number(y.id)===Number(id)))shows.push({id:Number(x.id),name:x.name,network:x.network?.name||x.webChannel?.name||'',status:x.status,image:x.image?.medium||'',airdate:e.airdate||'',airtime:e.airtime||'',next_episode:e.name||''});save(K.shows,shows);discover()}
function unfollow(id){shows=shows.filter(x=>Number(x.id)!==Number(id));save(K.shows,shows);myshows()}
async function details(id){let local=shows.find(x=>Number(x.id)===Number(id));let x=local;try{x=await fetch('https://api.tvmaze.com/shows/'+id).then(r=>r.json())}catch{}V.innerHTML='<h2>'+esc(x?.name||'Show Details')+'</h2><div class="card">'+(x?.image?.medium?'<img class="poster" src="'+esc(x.image.medium)+'">':'')+'<div class="sub" style="margin-top:12px">'+(x?.summary?x.summary.replace(/<[^>]+>/g,''):esc(local?.network||''))+'</div><button class="btn" style="margin-top:14px" onclick="go(\''+route+'\')">Back</button></div>'}
function more(){V.innerHTML='<h2>More</h2>'+[['catchup','Catch Up'],['night','Build My Night'],['services','Streaming Services'],['account','Account'],['alerts','Email Alerts'],['settings','Settings']].map(x=>'<button class="card" style="width:100%;text-align:left;font-weight:800" data-go="'+x[0]+'">'+x[1]+'</button>').join('')}
function catchup(){V.innerHTML='<h2>Catch Up</h2><div class="empty">Episode tracking remains connected to your saved shows.</div>'}function night(){V.innerHTML='<h2>Build My Night</h2><div class="card"><select class="search"><option>30 mins</option><option>1 hour</option><option selected>2 hours</option><option>3 hours</option><option>4 hours</option></select><div class="sub">Choose your watch-time budget.</div></div>'}const SERVICES=['Netflix','Prime Video','Peacock','Hulu','Disney+','HBO Max','Paramount+','Apple TV','Crunchyroll','YouTube','YouTube TV','ESPN','Tubi','Pluto TV','Roku Channel','Starz','AMC+','Discovery+','MGM+','Sling TV','Fubo','Philo','DIRECTV','BritBox','Shudder','Plex','ViX','Fandango at Home'];function servicePage(){V.innerHTML='<h2>Streaming Services</h2>'+SERVICES.map(x=>'<div class="card"><b>'+x+'</b></div>').join('')}function account(){V.innerHTML='<h2>Account</h2><div class="card">Cloud account features remain available in the existing backend.</div>'}function alerts(){V.innerHTML='<h2>Email Alerts</h2><div class="card">Cloud alert delivery remains connected to the existing backend configuration.</div>'}function settings(){V.innerHTML='<h2>Settings</h2><div class="card">MyTV Calendar V6</div>'}go('home');