const SUPABASE_URL="https://zvzrstudexfhzvnycfko.supabase.co";const SUPABASE_ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2enJzdHVkZXhmaHp2bnljZmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA5MzU2OTAsImV4cCI6MjEwNjUxMTY5MH0.U07bw1kyiU3HKE4j_if5HQlEkWAc3tqpYsv0vyp8brY";async function realProviders(name){try{const r=await fetch(SUPABASE_URL+"/functions/v1/where-to-watch?query="+encodeURIComponent(name),{headers:{apikey:SUPABASE_ANON,Authorization:"Bearer "+SUPABASE_ANON}});if(!r.ok)throw Error();return await r.json()}catch{return null}}async function oneSignalReady(){if(window.MyTVOneSignal)return window.MyTVOneSignal;return await new Promise((resolve,reject)=>{window.OneSignalDeferred=window.OneSignalDeferred||[];window.OneSignalDeferred.push(async OneSignal=>{window.MyTVOneSignal=OneSignal;resolve(OneSignal)});setTimeout(()=>reject(Error('Push service is still loading. Try again.')),10000)})}
async function enablePush(){const m=document.getElementById('push-msg');try{const os=await oneSignalReady();await os.Notifications.requestPermission();if(Notification.permission!=='granted'){if(m)m.textContent='Notifications were not enabled.';return}await os.User.PushSubscription.optIn();localStorage.setItem('mytv-push-enabled','1');if(m)m.textContent='Push notifications are enabled on this device.';renderPushButton()}catch(e){if(m)m.textContent='Could not enable notifications: '+e.message}}
async function disablePush(){const m=document.getElementById('push-msg');try{const os=await oneSignalReady();await os.User.PushSubscription.optOut();localStorage.removeItem('mytv-push-enabled');if(m)m.textContent='Push notifications are turned off on this device.';renderPushButton()}catch(e){if(m)m.textContent='Could not turn off notifications: '+e.message}}
async function renderPushButton(){const b=document.getElementById('push-toggle');if(!b)return;let on=false;try{const os=await oneSignalReady();on=Notification.permission==='granted'&&os.User.PushSubscription.optedIn}catch{}b.textContent=on?'Turn Off Push Notifications':'Enable Push Notifications';b.dataset.push=on?'off':'on'}
const K={shows:'mytv-v5-shows',watched:'mytv-v5-watched',prefs:'mytv-v5-prefs'};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let shows=load(K.shows,[]),watched=load(K.watched,{}),prefs=load(K.prefs,{}),favorites=load('mytv-v6-favorites',{}),tmdbSaved=load('mytv-v6-tmdb-saved',[]),route='home';const V=$('#view');
const nav=[['home','⌂','Home'],['calendar','▦','My Calendar'],['shows','♥','My Shows'],['discover','⌕','Discover'],['more','•••','More']];$('#mobileNav').innerHTML=nav.map(x=>'<button data-go="'+x[0]+'"><b>'+x[1]+'</b><span>'+x[2]+'</span></button>').join('');$('#side').innerHTML=[...nav.slice(0,4),['catchup','✓','Catch Up'],['night','★','Build My Night'],['settings','⚙','Settings']].map(x=>'<button data-go="'+x[0]+'" onclick="go(\''+x[0]+'\')">'+x[2]+'</button>').join('');document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});document.addEventListener('click',e=>{const b=e.target.closest('[data-push]');if(!b)return;e.preventDefault();if(b.dataset.push==='on')enablePush();else if(b.dataset.push==='off')disablePush();});
function animatePageMotion(){requestAnimationFrame(()=>{if(!V||!V.animate)return;V.animate([{opacity:0,transform:'translateY(18px) scale(.985)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:520,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})})}
function go(r){route=r;document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===r));const fn=({home,calendar,shows:myshows,discover,more,catchup,night,settings}[r]||home);fn();animatePageMotion();scrollTo(0,0)}
function mdY(d){if(!d)return'';let m=String(d).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?Number(m[2])+'/'+Number(m[3])+'/'+m[1]:d}function fmtTime(t){if(!t)return'';const m=String(t).match(/^(\d{1,2}):(\d{2})/);if(!m)return String(t);let h=Number(m[1]);const ap=h>=12?'PM':'AM';h=h%12||12;return h+':'+m[2]+' '+ap}async function refreshFollowedSchedules(){if(!shows.length)return;let changed=false;const fresh=await Promise.all(shows.map(async s=>{try{const x=await fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'?embed=nextepisode',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()});const e=x._embedded?.nextepisode||{};const n=applyVerifiedSchedule({...s,network:x.network?.name||x.webChannel?.name||s.network||'',webChannel:!!x.webChannel,status:x.status||s.status||'',airdate:e.airdate||'',airtime:e.airtime||'',airstamp:e.airstamp||'',next_episode:e.name||''});if(JSON.stringify(n)!==JSON.stringify(s))changed=true;return n}catch{return s}}));if(changed){shows=fresh;save(K.shows,shows);if(route==='home')home();else if(route==='calendar')calendar();else if(route==='shows')myshows()}}
const STREAM_RELEASE_TIMES={'Netflix':'03:00','Disney+':'03:00','HBO Max':'03:00','Max':'03:00','Paramount+':'03:00','AMC+':'03:00','ALLBLK':'03:00','BET+':'03:00','Hulu':'00:00','Apple TV+':'00:00','Peacock':'03:00'};
const VERIFIED_SHOW_TIMES={'Abbott Elementary':'20:30',"Special Forces: World's Toughest Test":'21:00'};
const VERIFIED_SHOW_SCHEDULES={'Abbott Elementary':{airdate:'2026-10-07',airtime:'20:30',network:'ABC'},"Special Forces: World's Toughest Test":{airtime:'21:00',network:'FOX'}};
function applyVerifiedSchedule(x){const v=VERIFIED_SHOW_SCHEDULES[String(x?.name||'').trim()];return v?{...x,...v,webChannel:false}:x}
shows=shows.map(applyVerifiedSchedule);
function normalizeBroadcastTime(t){if(!t)return'';const m=String(t).match(/^(\d{1,2}):(\d{2})/);if(!m)return String(t);let h=Number(m[1]),min=Number(m[2]);if(min>=1&&min<=7)min=0;else if(min>=28&&min<=37)min=30;else if(min>=53&&min<=59){h=(h+1)%24;min=0}return String(h).padStart(2,'0')+':'+String(min).padStart(2,'0')}
function verifiedTime(x){if(!x)return'';const forced=VERIFIED_SHOW_TIMES[String(x.name||'').trim()];if(forced)return fmtTime(forced);if(x.webChannel)return'';const v=normalizeBroadcastTime(x.airtime);return v?fmtTime(v):''}
function countdownText(x){const t=showStart(x);if(!Number.isFinite(t)||t>9e15)return'';const n=Date.now(),d=t-n;if(d<=0)return dayDiff(x.airdate)===0?'Airing today':'';const mins=Math.floor(d/60000);if(mins<60)return'Starts in '+Math.max(1,mins)+'m';const hrs=Math.floor(mins/60);if(hrs<24)return'Starts in '+hrs+'h '+(mins%60)+'m';const days=Math.floor(hrs/24);return'Starts in '+days+'d '+(hrs%24)+'h'}function favoriteMark(x){return favorites[String(x.id)]?' ★':''}function toggleFavorite(id){const k=String(id);if(favorites[k])delete favorites[k];else favorites[k]=true;save('mytv-v6-favorites',favorites);if(route==='shows')myshows();else home()}function scheduleLine(x){const a=[];if(x?.airdate)a.push(mdY(x.airdate));const t=verifiedTime(x);if(t)a.push(t);else if(x?.airdate)a.push('Time Pending');return a.join(' • ')||'Schedule pending'}function dayDiff(d){if(!d)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(d+'T00:00:00');return Math.round((b-a)/86400000)}function label(d){let n=dayDiff(d);if(n===null)return'Upcoming';if(n<0)return'Aired';if(n===0)return'Tonight';return new Date(d+'T00:00:00').toLocaleDateString('en-US',{weekday:'long'})}
function homeCard(x){return '<button class="home-tile" onclick="details('+Number(x.id)+')">'+(x.image?'<img src="'+esc(x.image)+'" alt="">':'<div class="home-poster-blank">▶</div>')+'<div class="home-tile-info"><b>'+esc(x.name+favoriteMark(x))+'</b><span>'+esc(scheduleLine(x))+'</span><span style="font-weight:800;color:#2f78d0">'+esc(countdownText(x))+'</span></div></button>'}
function calendarCard(x){return '<button class="calendar-card" onclick="details('+Number(x.id)+')"><div><b>'+esc(x.name)+'</b><div class="sub">'+esc(x.next_episode||x.network||'')+'</div></div><div class="calendar-when"><b>'+esc(label(x.airdate))+'</b><span>'+esc(scheduleLine(x))+'</span></div></button>'}
function myShowCard(x){return '<div class="card"><div class="showrow">'+(x.image?'<img class="poster" src="'+esc(x.image)+'">':'<div></div>')+'<div><div class="title">'+esc(x.name+favoriteMark(x))+'</div><div class="sub">'+esc(x.network||x.status||'')+'</div><span class="pill">'+esc(label(x.airdate))+'</span><div class="sub" style="margin-top:6px;font-weight:700">'+esc(scheduleLine(x))+'</div></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;width:100%;margin-top:12px"><button onclick="details('+Number(x.id)+')" class="btn">Details</button><button onclick="toggleFavorite('+Number(x.id)+')" class="btn">'+(favorites[String(x.id)]?'★ Favorite':'☆ Favorite')+'</button><button onclick="unfollow('+Number(x.id)+')" class="btn danger" style="grid-column:1/-1">Unfollow</button></div></div>'}

function startHomeWave(){
 const hand=document.getElementById('homeWaveHand');
 if(!hand)return;
 if(hand.getAnimations)hand.getAnimations().forEach(a=>a.cancel());
 if(hand.animate){
  hand.animate([
   {transform:'rotate(0deg)',offset:0},
   {transform:'rotate(14deg)',offset:.10},
   {transform:'rotate(-8deg)',offset:.20},
   {transform:'rotate(12deg)',offset:.30},
   {transform:'rotate(-5deg)',offset:.40},
   {transform:'rotate(7deg)',offset:.50},
   {transform:'rotate(0deg)',offset:.58},
   {transform:'rotate(0deg)',offset:1}
  ],{duration:8000,iterations:Infinity,easing:'ease-in-out'});
 }
}
function home(){const tonight=shows.filter(x=>dayDiff(x.airdate)===0).sort((a,b)=>showStart(a)-showStart(b)),coming=shows.filter(x=>{let n=dayDiff(x.airdate);return n>0}).sort((a,b)=>showStart(a)-showStart(b));const featured=(tonight.length?tonight:coming).slice(0,4),rest=coming.filter(x=>!featured.includes(x));V.innerHTML='<div class="home-head"><div><h1>Good '+(new Date().getHours()<12?'Morning':new Date().getHours()<17?'Afternoon':'Evening')+' <span id="homeWaveHand" style="display:inline-block;transform-origin:70% 75%">👋</span></h1><div class="sub">What’s on for you now and what’s coming next.</div></div><div class="fresh">● Live data ready</div></div><div class="stats"><div class="stat"><b>'+shows.length+'</b>Shows followed</div><div class="stat"><b>'+Object.keys(favorites).length+'</b>Favorites</div><div class="stat"><b>'+tonight.length+'</b>Tonight</div></div><h2>'+(tonight.length?'Tonight':'Coming Up')+'</h2><div class="home-grid">'+(featured.length?featured.map(homeCard).join(''):'<div class="empty">Nothing scheduled yet.</div>')+'</div>'+(rest.length?'<h2 class="home-section">More From Your Shows</h2><div class="home-grid home-grid-more">'+rest.map(homeCard).join('')+'</div>':'');requestAnimationFrame(startHomeWave)}

let calendarCursor=new Date();
function calKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function shiftCalendar(n){calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+n,1);calendar()}
function calendar(){
 const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),lead=first.getDay(),today=calKey(new Date());
 const byDate={};shows.forEach(s=>{if(s.airdate)(byDate[s.airdate]||(byDate[s.airdate]=[])).push(s)});
 Object.values(byDate).forEach(a=>a.sort((a,b)=>showStart(a)-showStart(b)));
 let cells='';for(let i=0;i<lead;i++)cells+='<div class="cal-day muted-day"></div>';
 for(let d=1;d<=last.getDate();d++){const key=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),a=byDate[key]||[];
  cells+='<div class="cal-day '+(key===today?'cal-today':'')+'"><div class="cal-num">'+d+(key===today?'<span>Today</span>':'')+'</div><div class="cal-events">'+a.map(x=>'<button onclick="details('+Number(x.id)+')"><b>'+esc(x.name)+'</b><span>'+esc(verifiedTime(x)||'Time Pending')+'</span></button>').join('')+'</div></div>'}
 const pending=shows.filter(x=>!x.airdate);
 V.innerHTML='<div class="cal-head"><div><h2>My Calendar</h2><div class="sub">Your shows, laid out like a real TV schedule.</div></div><div class="cal-controls"><button onclick="shiftCalendar(-1)">‹</button><b>'+first.toLocaleDateString('en-US',{month:'long',year:'numeric'})+'</b><button onclick="shiftCalendar(1)">›</button></div></div><div class="cal-week"><b>Sun</b><b>Mon</b><b>Tue</b><b>Wed</b><b>Thu</b><b>Fri</b><b>Sat</b></div><div class="cal-grid">'+cells+'</div>'+(pending.length?'<h3 class="cal-pending-title">Upcoming — Date Pending</h3><div class="cal-pending">'+pending.map(calendarCard).join('')+'</div>':'')
}function showStart(x){if(!x.airdate)return 9007199254740991;const d=(!x.webChannel&&x.airtime)?new Date(x.airdate+'T'+x.airtime+':00'):new Date(x.airdate+'T23:59:59');return isNaN(d)?9007199254740991:d.getTime()}
function myshows(){
 const tonight=shows.filter(x=>x.airdate&&dayDiff(x.airdate)===0).sort((a,b)=>showStart(a)-showStart(b));
 const coming=shows.filter(x=>x.airdate&&dayDiff(x.airdate)>0).sort((a,b)=>showStart(a)-showStart(b));
 const pending=shows.filter(x=>!x.airdate&&String(x.status||'').toLowerCase()!=='ended').sort((a,b)=>String(a.name).localeCompare(String(b.name)));
 const inactive=shows.filter(x=>(x.airdate&&dayDiff(x.airdate)<0)||(!x.airdate&&String(x.status||'').toLowerCase()==='ended')).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
 const section=(title,a,empty)=>'<section class="myshows-section"><h3>'+title+' <span class="sub">('+a.length+')</span></h3>'+(a.length?a.map(myShowCard).join(''):'<div class="empty">'+empty+'</div>')+'</section>';
 V.innerHTML='<h2>My Shows</h2><div class="sub" style="margin-bottom:16px">Schedule-first view • '+shows.length+' followed</div>'+section('On Tonight',tonight,'Nothing scheduled for tonight.')+section('Coming Up',coming,'No dated upcoming episodes yet.')+section('Upcoming — Date Pending',pending,'No continuing shows are waiting on a date.')+section('Not Currently Scheduled',inactive,'No inactive or unscheduled shows.');
}
async function discover(){V.innerHTML='<div class="discover-head"><h2>Discover</h2><div class="sub">Find your next show or movie.</div></div><div class="discover-chips"><button onclick="quickDiscover(\'action\')">Action</button><button onclick="quickDiscover(\'drama\')">Drama</button><button onclick="quickDiscover(\'reality\')">Reality</button><button onclick="quickDiscover(\'comedy\')">Comedy</button><button onclick="movieDiscover()">Movies</button></div><div class="discover-search"><input id="q" class="search" placeholder="Search shows and movies" onkeydown="if(event.key===\'Enter\')searchShows()"><button aria-label="Search" onclick="searchShows()">⌕</button></div><div class="discover-title"><b>Discover for You</b><span>Search or choose a category above</span></div><div id="results" class="discover-results"><div class="discover-empty">Explore shows and movies you’ll want to watch next.</div></div>'}
async function movieDiscover(){const e=$('#q');if(e){e.value='movie';searchShows('movie')}}function quickDiscover(q){const e=$('#q');if(e){e.value=q;searchShows()}}let discoverLastQuery='';
async function searchShows(qOverride){
 const q=(typeof qOverride==='string'?qOverride:($('#q')?.value||'')).trim(),R=$('#results');if(!q||!R)return;discoverLastQuery=q;R.innerHTML='<div class="sub">Searching shows, movies and actors…</div>';
 try{
  const [tm,tv]=await Promise.all([
   fetch(SUPABASE_URL+'/functions/v1/tmdb-search?query='+encodeURIComponent(q),{headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+SUPABASE_ANON}}).then(r=>r.ok?r.json():({results:[]})),
   fetch('https://api.tvmaze.com/search/shows?q='+encodeURIComponent(q)).then(r=>r.json()).catch(()=>[])
  ]);
  const movie=(tm.results||[]).filter(x=>x.type==='movie').map(x=>'<div class="card discover-pick" onclick="tmdbDetails('+Number(x.id)+',\'movie\')"><div class="showrow">'+(x.poster?'<img class="poster" src="'+esc(x.poster)+'">':'<div></div>')+'<div><div class="title">🎬 '+esc(x.title)+'</div><div class="sub">'+esc((x.actor?'With '+x.actor+' • ':'')+(x.year||'')+' • Movie')+'</div><div class="sub">Movie information only • Tap for details →</div></div></div></div>').join('');
  const show=tv.slice(0,8).map(z=>{const x=z.show,on=shows.some(y=>Number(y.id)===Number(x.id));return '<div class="card"><div class="showrow">'+(x.image?.medium?'<img class="poster" src="'+esc(x.image.medium)+'">':'<div></div>')+'<div><div class="title">📺 '+esc(x.name)+'</div><div class="sub">'+esc(x.network?.name||x.webChannel?.name||x.status||'TV')+'</div></div><div class="actions single">'+(on?'<button class="btn" disabled>Following</button>':'<button class="btn" onclick="follow('+Number(x.id)+')">Save + Follow</button>')+'</div></div></div>'}).join('');
  R.innerHTML=movie+show||'<div class="empty">No results.</div>';
 }catch{R.innerHTML='<div class="empty">Search is unavailable right now.</div>'}
}
async function tmdbDetails(id,type){const R=$('#results');if(!R)return;R.innerHTML='<div class="sub">Loading details…</div>';try{const r=await fetch(SUPABASE_URL+'/functions/v1/tmdb-search?id='+id+'&type='+encodeURIComponent(type),{headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+SUPABASE_ANON}});const d=await r.json(),x=d.detail;if(!x)throw Error();R.innerHTML='<button class="btn" onclick="searchShows(discoverLastQuery)">← Back to results</button><div class="card" style="margin-top:12px">'+(x.poster?'<img class="poster" src="'+esc(x.poster)+'">':'')+'<div class="title" style="margin-top:10px">'+esc(x.title)+'</div><div class="sub">'+esc((x.year||'')+' • '+(type==='movie'?'Movie':'TV'))+'</div><div style="margin-top:10px">'+esc(x.overview||'No description available.')+'</div></div><h3>Where to Watch</h3><div id="tmdb-wtw" class="card"><div class="sub">Checking streaming availability…</div></div>';const W=$('#tmdb-wtw'),p=await realProviders(x.title);if(W)W.innerHTML=p?.providers?.length?p.providers.map(a=>'<div class="sub">'+esc(a.name||a.provider_name||'Provider')+'</div>').join(''):'<div class="empty">No verified U.S. streaming options found.</div>'}catch{R.innerHTML='<div class="empty">Details are unavailable right now.</div>'}}

async function follow(id){try{let x=await fetch('https://api.tvmaze.com/shows/'+id+'?embed=nextepisode').then(r=>{if(!r.ok)throw Error();return r.json()});let e=x._embedded?.nextepisode||{};let added=false;if(!shows.some(y=>Number(y.id)===Number(id))){shows.push({id:Number(x.id),name:x.name,network:x.network?.name||x.webChannel?.name||'',webChannel:!!x.webChannel,status:x.status,image:x.image?.medium||'',airdate:e.airdate||'',airtime:e.airtime||'',airstamp:e.airstamp||'',next_episode:e.name||''});save(K.shows,shows);added=true}alert(added?'✓ '+x.name+' has been added to My Shows.':x.name+' is already in My Shows.');if(route==='discover')await searchShows(discoverLastQuery)}catch{alert('The show could not be added right now. Please try again.')}}
function unfollow(id){shows=shows.filter(x=>Number(x.id)!==Number(id));save(K.shows,shows);myshows()}
async function details(id){
  let local=shows.find(x=>Number(x.id)===Number(id)),x=local;
  try{x=await fetch('https://api.tvmaze.com/shows/'+id).then(r=>{if(!r.ok)throw Error();return r.json()})}catch{}
  const name=x?.name||local?.name||'Show Details';
  V.innerHTML='<h2>'+esc(name)+'</h2><div class="card">'+(x?.image?.medium?'<img class="poster" src="'+esc(x.image.medium)+'">':'')+'<div class="sub" style="margin-top:12px">'+(x?.summary?x.summary.replace(/<[^>]+>/g,''):esc(local?.network||''))+'</div></div><h3>Where to Watch</h3><div id="wtw" class="card"><div class="sub">Checking verified U.S. streaming availability…</div></div><button class="btn" style="margin-top:14px" onclick="go(\''+route+'\')">Back</button>';
  const W=$('#wtw'),d=await realProviders(name);
  if(!W)return;
  if(!d){W.innerHTML='<div class="empty">Where to Watch is unavailable right now.</div>';return}
  if(!d.found||!d.providers?.length){W.innerHTML='<div class="empty">No verified U.S. streaming options were found for this show.</div>';return}
  const labels={flatrate:'Stream',free:'Free',ads:'With Ads',rent:'Rent',buy:'Buy'};
  W.innerHTML='<div class="sub" style="margin-bottom:10px">Verified provider availability for the U.S.</div>'+d.providers.map(p=>'<div style="display:flex;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid #e7edf5">'+(p.logo?'<img src="'+esc(p.logo)+'" alt="" style="width:38px;height:38px;border-radius:8px;object-fit:cover">':'')+'<div><b>'+esc(p.name)+'</b><div class="sub">'+esc(labels[p.type]||p.type)+'</div></div></div>').join('')+(d.link?'<a class="btn" style="display:inline-block;text-decoration:none;margin-top:12px" href="'+esc(d.link)+'" target="_blank" rel="noopener">View Watch Options</a>':'')
}
function more(){V.innerHTML='<h2>More</h2>'+[['catchup','Catch Up'],['night','Build My Night'],['settings','Settings']].map(x=>'<button class="card" style="width:100%;text-align:left;font-weight:800" data-go="'+x[0]+'" onclick="go(\''+x[0]+'\')">'+x[1]+'</button>').join('')}
async function catchup(){
  V.innerHTML='<h2>Catch Up</h2><div class="sub" style="margin-bottom:16px">Aired episodes from your followed shows. Mark episodes watched as you catch up.</div><div id="catchupList"><div class="empty">Loading episodes…</div></div>';
  const R=$('#catchupList');
  if(!shows.length){R.innerHTML='<div class="empty">Follow shows from Discover and their aired episodes will appear here.</div>';return}
  const today=new Date();today.setHours(23,59,59,999);
  const results=await Promise.all(shows.map(async s=>{try{
    const eps=await fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'/episodes').then(r=>{if(!r.ok)throw Error();return r.json()});
    return {show:s,eps:eps.filter(e=>e.airdate&&new Date(e.airdate+'T23:59:59')<=today)}
  }catch{return {show:s,eps:[],error:true}}}));
  let blocks=results.map(({show,eps,error})=>{
    if(error)return '<div class="card"><div class="title">'+esc(show.name)+'</div><div class="sub">Episode data unavailable right now.</div></div>';
    if(!eps.length)return '';
    eps.sort((a,b)=>String(b.airdate).localeCompare(String(a.airdate))||Number(b.id)-Number(a.id));
    return '<section><h3>'+esc(show.name)+'</h3>'+eps.map(e=>{
      const key=String(e.id),done=!!watched[key],se='S'+String(e.season??0).padStart(2,'0')+'E'+String(e.number??0).padStart(2,'0');
      return '<div class="card"><div class="title">'+esc(se+' • '+(e.name||'Episode'))+'</div><div class="sub">'+esc(mdY(e.airdate))+'</div><button class="btn" style="margin-top:10px;'+(done?'background:#19a974':'')+'" onclick="toggleWatched('+Number(e.id)+')">'+(done?'✓ Watched':'Mark Watched')+'</button></div>'
    }).join('')+'</section>'
  }).join('');
  R.innerHTML=blocks||'<div class="empty">No aired episodes found for your followed shows.</div>'
}
function toggleWatched(id){const k=String(id);if(watched[k])delete watched[k];else watched[k]=true;save(K.watched,watched);catchup()}function night(){V.innerHTML='<h2>Build My Night</h2><div class="card"><select class="search"><option>30 mins</option><option>1 hour</option><option selected>2 hours</option><option>3 hours</option><option>4 hours</option></select><div class="sub">Choose your watch-time budget.</div></div>'}function settings(){V.innerHTML='<h2>Settings</h2><div class="card"><div class="title">Push Notifications</div><div class="sub">Get My TV Calendar reminders and show updates on this device, powered by OneSignal.</div><button type="button" id="push-toggle" class="btn" data-push="on" style="margin-top:12px">Enable Push Notifications</button><div id="push-msg" class="sub" style="margin-top:10px"></div></div><div class="card">My TV Calendar V6.3.50</div>';renderPushButton()}go('home');refreshFollowedSchedules();