const SUPABASE_URL="https://zvzrstudexfhzvnycfko.supabase.co";const SUPABASE_ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2enJzdHVkZXhmaHp2bnljZmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA5MzU2OTAsImV4cCI6MjEwNjUxMTY5MH0.U07bw1kyiU3HKE4j_if5HQlEkWAc3tqpYsv0vyp8brY";const SB=window.supabase?.createClient?window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON):null;async function realProviders(name,type='tv',id=''){try{const r=await fetch(SUPABASE_URL+"/functions/v1/where-to-watch?query="+encodeURIComponent(name)+"&type="+encodeURIComponent(type)+(id?"&id="+encodeURIComponent(id):""),{headers:{apikey:SUPABASE_ANON,Authorization:"Bearer "+SUPABASE_ANON}});if(!r.ok)throw Error();return await r.json()}catch{return null}}let oneSignalInitPromise=null;
async function oneSignalReady(){
 if(window.MyTVOneSignal)return window.MyTVOneSignal;
 if(window.MyTVOneSignalError)throw Error('OneSignal initialization failed: '+(window.MyTVOneSignalError.message||String(window.MyTVOneSignalError)));
 if(oneSignalInitPromise)return oneSignalInitPromise;
 oneSignalInitPromise=new Promise((resolve,reject)=>{
  let done=false;
  const ok=()=>{if(done)return;done=true;cleanup();resolve(window.MyTVOneSignal)},
        bad=()=>{if(done)return;done=true;cleanup();reject(Error('OneSignal initialization failed: '+(window.MyTVOneSignalError?.message||String(window.MyTVOneSignalError||'unknown error'))))},
        cleanup=()=>{clearTimeout(timer);window.removeEventListener('mytv-onesignal-ready',ok);window.removeEventListener('mytv-onesignal-error',bad)};
  window.addEventListener('mytv-onesignal-ready',ok,{once:true});
  window.addEventListener('mytv-onesignal-error',bad,{once:true});
  if(window.MyTVOneSignal)return ok();
  if(window.MyTVOneSignalError)return bad();
  const timer=setTimeout(()=>{if(done)return;done=true;cleanup();reject(Error('OneSignal SDK did not initialize within 20 seconds.'))},20000);
 });
 return oneSignalInitPromise;
}
async function notificationSync(payload){const {data:{session}}=await SB.auth.getSession();if(!session)return false;const r=await fetch(SUPABASE_URL+'/functions/v1/notification-sync',{method:'POST',headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify(payload)});return r.ok}
async function syncNotificationPrefs(){const p=notificationPrefs();return notificationSync({type:'preferences',preferences:p,push_enabled:localStorage.getItem('mytv-push-enabled')==='1',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/New_York'})}
async function syncNotificationTitles(){const items=[...shows.map(x=>({media_type:'show',external_id:String(x.id),title:x.name,event_date:x.airdate||null,event_time:x.airtime||null})),...movieWatchlist.map(x=>({media_type:'movie',external_id:String(x.id),title:x.title,event_date:x.release_date||null}))];return notificationSync({type:'sync',items})}
async function reconcileNotificationRegistration(){try{const user=await getSessionUser();if(!user)return false;const os=await oneSignalReady();let sid=null;for(let i=0;i<12&&!sid;i++){sid=os.User?.PushSubscription?.id||null;if(!sid)await new Promise(r=>setTimeout(r,500))}const granted=Notification.permission==='granted';const opted=!!os.User?.PushSubscription?.optedIn;if(!granted||!opted||!sid){console.warn('Push registration unavailable',{granted,opted,hasSubscriptionId:!!sid});return false}localStorage.setItem('mytv-push-enabled','1');const registered=await notificationSync({type:'register',subscription_id:sid,enabled:true});if(!registered)throw Error('Device registration sync failed');await syncNotificationPrefs();await syncNotificationTitles();return true}catch(e){console.warn('Notification reconciliation failed',e);return false}}
async function enablePush(){
 const m=document.getElementById('push-msg'),b=document.getElementById('push-toggle');
 try{
  if(m)m.textContent='Starting push service…';if(b)b.disabled=true;
  if(!('Notification' in window))throw Error('This browser does not support notifications.');
  if(!('serviceWorker' in navigator))throw Error('This browser does not support push service workers.');
  const workerUrl=new URL('push/onesignal/OneSignalSDKWorker.js',location.href).href;
  const workerCheck=await fetch(workerUrl,{cache:'no-store'});
  if(!workerCheck.ok)throw Error('Push worker could not be loaded ('+workerCheck.status+').');
  const os=await oneSignalReady();
  if(m)m.textContent='Requesting notification permission…';
  const permission=await os.Notifications.requestPermission();
  if(Notification.permission!=='granted'){if(m)m.textContent='Notifications were not enabled ('+Notification.permission+').';return}
  if(m)m.textContent='Registering this device…';
  await os.User.PushSubscription.optIn();
  let sid=null;
  for(let i=0;i<20&&!sid;i++){sid=os.User?.PushSubscription?.id||null;if(!sid)await new Promise(r=>setTimeout(r,250))}
  if(!sid)throw Error('Push permission was granted, but no subscription ID was created.');
  const registered=await notificationSync({type:'register',subscription_id:sid,enabled:true});
  if(!registered)throw Error('Push subscription was created, but backend registration failed.');
  localStorage.setItem('mytv-push-enabled','1');
  await syncNotificationPrefs();await syncNotificationTitles();
  if(m)m.textContent='Push notifications are enabled on this device.';
  await renderPushButton();
 }catch(e){
  console.error('Push enable failed',e);
  if(m)m.textContent='Could not enable notifications: '+(e&&e.message?e.message:String(e));
 }finally{if(b)b.disabled=false}
}
async function disablePush(){const m=document.getElementById('push-msg');try{const os=await oneSignalReady();const sid=os.User.PushSubscription.id||null;await os.User.PushSubscription.optOut();localStorage.removeItem('mytv-push-enabled');await notificationSync({type:'register',subscription_id:sid,enabled:false});await syncNotificationPrefs();if(m)m.textContent='Push notifications are turned off on this device.';renderPushButton()}catch(e){if(m)m.textContent='Could not turn off notifications: '+e.message}}
async function renderPushButton(){const b=document.getElementById('push-toggle');if(!b)return;const saved=localStorage.getItem('mytv-push-enabled')==='1';let on=saved;b.disabled=true;b.textContent=saved?'Turn Off Push Notifications':'Checking Push Notifications…';try{const os=await oneSignalReady();let sid=null;for(let i=0;i<12&&!sid;i++){sid=os.User?.PushSubscription?.id||null;if(!sid)await new Promise(r=>setTimeout(r,250))}const live=Notification.permission==='granted'&&!!os.User?.PushSubscription?.optedIn&&!!sid;if(live){on=true;localStorage.setItem('mytv-push-enabled','1');await notificationSync({type:'register',subscription_id:sid,enabled:true});await syncNotificationPrefs()}else if(Notification.permission==='denied'){on=false;localStorage.removeItem('mytv-push-enabled')}}catch(e){console.warn('Push state check unavailable; preserving saved choice',e)}b.textContent=on?'Turn Off Push Notifications':'Enable Push Notifications';b.dataset.push=on?'off':'on';b.disabled=false}
const K={shows:'mytv-v5-shows',watched:'mytv-v5-watched',prefs:'mytv-v5-prefs'};const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let shows=load(K.shows,[]),watched=load(K.watched,{}),prefs=load(K.prefs,{}),favorites=load('mytv-v6-favorites',{}),tmdbSaved=load('mytv-v6-tmdb-saved',[]),movieWatchlist=load('mytv-v6-movie-watchlist',[]),route='home';const V=$('#view');
const nav=[['home','⌂','Home'],['calendar','▦','My Calendar'],['shows','♥','My Shows'],['discover','⌕','Discover'],['more','•••','More']];$('#mobileNav').innerHTML=nav.map(x=>'<button data-go="'+x[0]+'"><b>'+x[1]+'</b><span>'+x[2]+'</span></button>').join('');$('#side').innerHTML=[...nav.slice(0,4),['catchup','✓','Catch Up'],['night','★','Build My Night'],['settings','⚙','Settings'],['subscriptions','◈','Subscriptions']].map(x=>'<button data-go="'+x[0]+'" onclick="go(\''+x[0]+'\')">'+x[2]+'</button>').join('');document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)go(b.dataset.go)});document.addEventListener('click',e=>{const b=e.target.closest('[data-push]');if(!b)return;e.preventDefault();if(b.dataset.push==='on')enablePush();else if(b.dataset.push==='off')disablePush();});
function animatePageMotion(){requestAnimationFrame(()=>{if(!V||!V.animate)return;V.animate([{opacity:0,transform:'translateY(18px) scale(.985)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:520,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})})}
async function go(r){const user=await getSessionUser();const privateRoutes=['home','calendar','shows','catchup','night'];if(!user&&privateRoutes.includes(r)){route='subscriptions';document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go==='subscriptions'));await subscriptions();animatePageMotion();scrollTo(0,0);return}route=r;document.querySelectorAll('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===r));const fn=({home,calendar,shows:myshows,discover,more,catchup,night,settings,subscriptions,upgrade:subscriptions}[r]||home);await fn();animatePageMotion();scrollTo(0,0)}
function mdY(d){if(!d)return'';let m=String(d).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?Number(m[2])+'/'+Number(m[3])+'/'+m[1]:d}function fmtTime(t){if(!t)return'';const m=String(t).match(/^(\d{1,2}):(\d{2})/);if(!m)return String(t);let h=Number(m[1]);const ap=h>=12?'PM':'AM';h=h%12||12;return h+':'+m[2]+' '+ap}async function refreshFollowedSchedules(){if(!shows.length)return;let changed=false;const today=new Date(),todayKey=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');const fresh=await Promise.all(shows.map(async s=>{try{const [x,eps]=await Promise.all([fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'?embed=nextepisode',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}),fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'/episodes',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[])]);const e=x._embedded?.nextepisode||{};rememberEpisodes(s.id,eps);const todays=(Array.isArray(eps)?eps:[]).filter(ep=>ep.airdate===todayKey);const current=todays.length?todays[0]:null;const keepToday=s.airdate===todayKey&&e.airdate!==todayKey;const n=applyVerifiedSchedule({...s,network:x.network?.name||x.webChannel?.name||s.network||'',webChannel:!!x.webChannel,status:x.status||s.status||'',airdate:current?todayKey:(keepToday?s.airdate:(e.airdate||s.airdate||'')),airtime:current?(current.airtime||s.airtime||''):(keepToday?s.airtime:(e.airtime||s.airtime||'')),airstamp:current?(current.airstamp||s.airstamp||''):(keepToday?s.airstamp:(e.airstamp||s.airstamp||'')),next_episode:current?(todays.length>1?todays.length+' episodes today':(current.name||s.next_episode||'')):(keepToday?s.next_episode:(e.name||s.next_episode||''))});if(JSON.stringify(n)!==JSON.stringify(s))changed=true;return n}catch{return s}}));if(changed){shows=fresh;save(K.shows,shows);syncNotificationTitles();if(route==='home')home();else if(route==='calendar')calendar();else if(route==='shows')myshows()}}
const EPISODE_HISTORY_KEY='mytv-v6-episode-history';let episodeHistory=load(EPISODE_HISTORY_KEY,{});function rememberEpisodes(id,eps){if(!Array.isArray(eps))return;const key=String(id);const prior=episodeHistory[key]||[];const map=new Map(prior.map(e=>[String(e.id||e.airdate+'|'+e.name),e]));eps.forEach(e=>{if(e.airdate){const entry={id:e.id,airdate:e.airdate,airtime:e.airtime||'',name:e.name||''};map.set(String(e.id||e.airdate+'|'+e.name),entry)}});episodeHistory[key]=Array.from(map.values()).sort((a,b)=>a.airdate.localeCompare(b.airdate));save(EPISODE_HISTORY_KEY,episodeHistory)}
const STREAM_RELEASE_TIMES={'Netflix':'03:00','Disney+':'03:00','HBO Max':'03:00','Max':'03:00','Paramount+':'03:00','AMC+':'03:00','ALLBLK':'03:00','BET+':'03:00','Hulu':'00:00','Apple TV+':'00:00','Peacock':'03:00'};
const VERIFIED_SHOW_TIMES={'Abbott Elementary':'20:30',"Special Forces: World's Toughest Test":'21:00'};
const VERIFIED_SHOW_SCHEDULES={'Abbott Elementary':{airdate:'2026-10-07',airtime:'20:30',network:'ABC'},"Special Forces: World's Toughest Test":{airtime:'21:00',network:'FOX'}};
function applyVerifiedSchedule(x){const v=VERIFIED_SHOW_SCHEDULES[String(x?.name||'').trim()];return v?{...x,...v,webChannel:false}:x}
shows=shows.map(applyVerifiedSchedule);
function normalizeBroadcastTime(t){if(!t)return'';const m=String(t).match(/^(\d{1,2}):(\d{2})/);if(!m)return String(t);let h=Number(m[1]),min=Number(m[2]);if(min>=1&&min<=7)min=0;else if(min>=28&&min<=37)min=30;else if(min>=53&&min<=59){h=(h+1)%24;min=0}return String(h).padStart(2,'0')+':'+String(min).padStart(2,'0')}
function verifiedTime(x){if(!x)return'';const forced=VERIFIED_SHOW_TIMES[String(x.name||'').trim()];if(forced)return fmtTime(forced);const exact=normalizeBroadcastTime(x.airtime);return exact?fmtTime(exact):''}
function countdownText(x){const t=showStart(x);if(!Number.isFinite(t)||t>9e15)return'';const n=Date.now(),d=t-n;if(d<=0)return dayDiff(x.airdate)===0?'Airing today':'';const mins=Math.floor(d/60000);if(mins<60)return'Starts in '+Math.max(1,mins)+'m';const hrs=Math.floor(mins/60);if(hrs<24)return'Starts in '+hrs+'h '+(mins%60)+'m';const days=Math.floor(hrs/24);return'Starts in '+days+'d '+(hrs%24)+'h'}function favoriteMark(x){return favorites[String(x.id)]?' ★':''}function toggleFavorite(id){const k=String(id);if(favorites[k])delete favorites[k];else favorites[k]=true;save('mytv-v6-favorites',favorites);if(route==='shows')myshows();else home()}function scheduleLine(x){const a=[];if(x?.airdate)a.push(mdY(x.airdate));const t=verifiedTime(x);if(t)a.push(t);else if(x?.airdate)a.push('Time Pending');return a.join(' • ')||'Schedule pending'}function dayDiff(d){if(!d)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(d+'T00:00:00');return Math.round((b-a)/86400000)}function label(d){let n=dayDiff(d);if(n===null)return'Upcoming';if(n<0)return'Aired';if(n===0)return'Tonight';return new Date(d+'T00:00:00').toLocaleDateString('en-US',{weekday:'long'})}
function homeCard(x){return '<button class="home-tile" onclick="details('+Number(x.id)+')">'+(x.image?'<img src="'+esc(x.image)+'" alt="">':'<div class="home-poster-blank">▶</div>')+'<div class="home-tile-info"><b>'+esc(x.name+favoriteMark(x))+'</b><span>'+esc(scheduleLine(x))+'</span><span style="font-weight:800;color:#2f78d0">'+esc(countdownText(x))+'</span></div></button>'}
function calendarCard(x){return '<button class="calendar-card" onclick="details('+Number(x.id)+')"><div><b>'+esc(x.name)+'</b><div class="sub">'+esc(x.next_episode||x.network||'')+'</div></div><div class="calendar-when"><b>'+esc(label(x.airdate))+'</b><span>'+esc(scheduleLine(x))+'</span></div></button>'}
function myShowCard(x){return '<div class="card"><div class="showrow">'+(x.image?'<img class="poster" src="'+esc(x.image)+'">':'<div></div>')+'<div><div class="title">'+esc(x.name+favoriteMark(x))+'</div><div class="sub">'+esc(x.network||x.status||'')+'</div><span class="pill">'+esc(label(x.airdate))+'</span><div class="sub" style="margin-top:6px;font-weight:700">'+esc(scheduleLine(x))+'</div></div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;width:100%;margin-top:12px"><button onclick="details('+Number(x.id)+')" class="btn">Details</button><button onclick="toggleFavorite('+Number(x.id)+')" class="btn">'+(favorites[String(x.id)]?'★ Favorite':'☆ Favorite')+'</button><button onclick="unfollow('+Number(x.id)+')" class="btn danger" style="grid-column:1/-1">Unfollow</button></div></div>'}

function startHomeWave(){
 const hand=document.getElementById('homeWaveHand');
 if(!hand)return;
 if(hand.getAnimations)hand.getAnimations().forEach(a=>a.cancel());
 if(hand.animate){
  hand.animate([
   {transform:'rotate(0deg)',offset:0},
   {transform:'rotate(14deg)',offset:.10},
   {transform:'rotate(-8deg)',offset:.20},
   {transform:'rotate(12deg)',offset:.30},
   {transform:'rotate(-5deg)',offset:.40},
   {transform:'rotate(7deg)',offset:.50},
   {transform:'rotate(0deg)',offset:.58},
   {transform:'rotate(0deg)',offset:1}
  ],{duration:8000,iterations:Infinity,easing:'ease-in-out'});
 }
}
function home(){const tonight=shows.filter(x=>dayDiff(x.airdate)===0).sort((a,b)=>showStart(a)-showStart(b)),coming=shows.filter(x=>{let n=dayDiff(x.airdate);return n>0}).sort((a,b)=>showStart(a)-showStart(b));const featured=(tonight.length?tonight:coming).slice(0,4),rest=coming.filter(x=>!featured.includes(x));V.innerHTML='<div class="home-head"><div><h1>Good '+(new Date().getHours()<12?'Morning':new Date().getHours()<17?'Afternoon':'Evening')+' <span id="homeWaveHand" style="display:inline-block;transform-origin:70% 75%">👋</span></h1><div class="sub">What’s on for you now and what’s coming next.</div></div><div class="fresh">● Live data ready</div></div><div class="stats"><div class="stat"><b>'+shows.length+'</b>Shows followed</div><div class="stat"><b>'+Object.keys(favorites).length+'</b>Favorites</div><div class="stat"><b>'+tonight.length+'</b>Tonight</div></div><h2>'+(tonight.length?'Tonight':'Coming Up')+'</h2><div class="home-grid">'+(featured.length?featured.map(homeCard).join(''):'<div class="empty">Nothing scheduled yet.</div>')+'</div>'+(rest.length?'<h2 class="home-section">More From Your Shows</h2><div class="home-grid home-grid-more">'+rest.map(homeCard).join('')+'</div>':'');requestAnimationFrame(startHomeWave)}

let calendarCursor=new Date();
function calKey(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function shiftCalendar(n){calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+n,1);calendar()}
function calendar(){
 const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),lead=first.getDay(),today=calKey(new Date());
 const byDate={};shows.forEach(s=>{const entries=(episodeHistory[String(s.id)]||[]).filter(e=>e.airdate);if(s.airdate&&!entries.some(e=>e.airdate===s.airdate))entries.push({airdate:s.airdate,airtime:s.airtime||'',name:s.next_episode||''});const dates=[...new Set(entries.filter(e=>!e.id||!watched[String(e.id)]).map(e=>e.airdate))];dates.forEach(date=>{const day=entries.filter(e=>e.airdate===date&&(!e.id||!watched[String(e.id)]));const first=day[0];const item={...s,airdate:date,airtime:first?.airtime||'',next_episode:day.length>1?day.length+' episodes':first?.name||''};(byDate[date]||(byDate[date]=[])).push(item)})});
 Object.keys(byDate).forEach(date=>{const unique=new Map();byDate[date].forEach(item=>{const key=String(item.id||item.name).toLowerCase();if(!unique.has(key))unique.set(key,item)});byDate[date]=Array.from(unique.values()).sort((a,b)=>showStart(a)-showStart(b))});
 let cells='';for(let i=0;i<lead;i++)cells+='<div class="cal-day muted-day"></div>';
 for(let d=1;d<=last.getDate();d++){const key=y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0'),a=byDate[key]||[];
  cells+='<div class="cal-day '+(key===today?'cal-today':'')+'"><div class="cal-num">'+d+(key===today?'<span>Today</span>':'')+'</div><div class="cal-events">'+a.map(x=>'<button onclick="details('+Number(x.id)+')"><b>'+esc(x.name)+'</b><span>'+esc(verifiedTime(x)||'Time Pending')+'</span></button>').join('')+'</div></div>'}
 const pending=shows.filter(x=>!x.airdate);
 V.innerHTML='<div class="cal-head"><div><h2>My Calendar</h2><div class="sub">Your shows, laid out like a real TV schedule.</div></div><div class="cal-controls"><button onclick="shiftCalendar(-1)">‹</button><b>'+first.toLocaleDateString('en-US',{month:'long',year:'numeric'})+'</b><button onclick="shiftCalendar(1)">›</button></div></div><div class="cal-week"><b>Sun</b><b>Mon</b><b>Tue</b><b>Wed</b><b>Thu</b><b>Fri</b><b>Sat</b></div><div class="cal-grid">'+cells+'</div>'+(pending.length?'<h3 class="cal-pending-title">Upcoming — Date Pending</h3><div class="cal-pending">'+pending.map(calendarCard).join('')+'</div>':'')
}function showStart(x){if(!x.airdate)return 9007199254740991;const raw=normalizeBroadcastTime(x.airtime);const d=raw?new Date(x.airdate+'T'+raw+':00'):new Date(x.airdate+'T23:59:59');return isNaN(d)?9007199254740991:d.getTime()}
function myshows(){showMyShowsTab('tv')}
async function showMyShowsTab(tab){
 if(tab==='movies'&&!(await hasPlan('plus'))){return lockedFeature('Movie Watchlist','Calendar+ or higher')}
 if(tab==='movies'){V.innerHTML='<h2>My Shows</h2><div class="myshows-tabs"><button onclick="showMyShowsTab(\'tv\')">TV Shows</button><button class="active" onclick="showMyShowsTab(\'movies\')">Movie Watchlist</button></div><div class="sub watchlist-count">'+movieWatchlist.length+' saved movie'+(movieWatchlist.length===1?'':'s')+'</div>'+movieWatchlistView();return}
 const tonight=shows.filter(x=>x.airdate&&dayDiff(x.airdate)===0).sort((a,b)=>showStart(a)-showStart(b));
 const coming=shows.filter(x=>x.airdate&&dayDiff(x.airdate)>0).sort((a,b)=>showStart(a)-showStart(b));
 const pending=shows.filter(x=>!x.airdate&&String(x.status||'').toLowerCase()!=='ended').sort((a,b)=>String(a.name).localeCompare(String(b.name)));
 const inactive=shows.filter(x=>(x.airdate&&dayDiff(x.airdate)<0)||(!x.airdate&&String(x.status||'').toLowerCase()==='ended')).sort((a,b)=>String(a.name).localeCompare(String(b.name)));
 const section=(title,a,empty)=>'<section class="myshows-section"><h3>'+title+' <span class="sub">('+a.length+')</span></h3>'+(a.length?a.map(myShowCard).join(''):'<div class="empty">'+empty+'</div>')+'</section>';
 V.innerHTML='<h2>My Shows</h2><div class="myshows-tabs"><button class="active" onclick="showMyShowsTab(\'tv\')">TV Shows</button><button onclick="showMyShowsTab(\'movies\')">Movie Watchlist</button></div><div class="sub" style="margin-bottom:16px">Schedule-first view • '+shows.length+' followed</div>'+section('On Tonight',tonight,'Nothing scheduled for tonight.')+section('Coming Up',coming,'No dated upcoming episodes yet.')+section('Upcoming — Date Pending',pending,'No continuing shows are waiting on a date.')+section('Not Currently Scheduled',inactive,'No inactive or unscheduled shows.');
}
function movieReleaseCountdown(d){if(!d)return'Release date pending';const today=new Date();today.setHours(0,0,0,0);const release=new Date(d+'T00:00:00');const days=Math.ceil((release-today)/86400000);if(days>1)return'⏳ '+days+' days until release';if(days===1)return'⏳ Releases tomorrow';if(days===0)return'🎬 Releases today';return'✓ Released'}
function movieWatchlistView(){if(!movieWatchlist.length)return '<div class="empty movie-watchlist-empty">No movies saved yet. Add movies from Discover → Movies.</div>';return '<div class="movie-grid watchlist-grid">'+movieWatchlist.map(x=>'<div class="movie-card">'+(x.poster?'<img src="'+esc(x.poster)+'" alt="">':'<div class="movie-no-poster">🎬</div>')+'<div class="movie-card-info"><b>'+esc(x.title)+'</b><span>'+(x.release_date&&x.release_date>=new Date().toISOString().slice(0,10)?'🎟️ In Theaters — '+esc(new Date(x.release_date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})):esc(x.release_date?new Date(x.release_date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Release date pending'))+'</span><span class="movie-countdown">'+esc(movieReleaseCountdown(x.release_date))+'</span><button class="btn" onclick="watchlistMovieDetails('+Number(x.id)+')">Details & Where to Watch</button><button class="movie-remove" onclick="removeMovieWatchlist('+Number(x.id)+')">Remove</button></div></div>').join('')+'</div>'}
function removeMovieWatchlist(id){movieWatchlist=movieWatchlist.filter(x=>Number(x.id)!==Number(id));save('mytv-v6-movie-watchlist',movieWatchlist);showMyShowsTab('movies')}
async function watchlistMovieDetails(id){const x=movieWatchlist.find(m=>Number(m.id)===Number(id));V.innerHTML='<h2>'+esc(x?.title||'Movie Details')+'</h2><button class="btn" onclick="showMyShowsTab(\'movies\')">← Movie Watchlist</button><div id="watchlist-movie-detail" style="margin-top:12px"><div class="sub">Loading details…</div></div>';const R=$('#watchlist-movie-detail');try{const r=await fetch(SUPABASE_URL+'/functions/v1/tmdb-search?id='+id+'&type=movie',{headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+SUPABASE_ANON}}),d=await r.json(),m=d.detail;if(!m)throw Error();const upcoming=m.release_date&&m.release_date>=new Date().toISOString().slice(0,10);R.innerHTML='<div class="card">'+(m.poster?'<img class="poster" src="'+esc(m.poster)+'">':'')+'<div class="title" style="margin-top:10px">'+esc(m.title)+'</div><div class="sub">'+esc((m.year||'')+' • Movie')+'</div>'+(upcoming?'<div class="theater-badge">🎟️ In Theaters — '+esc(new Date(m.release_date+'T12:00:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'}))+'</div>':'')+'<div style="margin-top:10px">'+esc(m.overview||'No description available.')+'</div></div><h3>'+(upcoming?'Theatrical Release':'Where to Watch')+'</h3><div id="watchlist-wtw" class="card"><div class="sub">Checking streaming availability…</div></div>';const W=$('#watchlist-wtw'),p=await realProviders(m.title,'movie',m.id);if(W)W.innerHTML=p?.providers?.length?p.providers.map(a=>'<div class="sub">'+esc(a.name||a.provider_name||'Provider')+'</div>').join(''):'<div class="empty">No verified U.S. streaming options found.</div>'}catch{R.innerHTML='<div class="empty">Movie details are unavailable right now.</div>'}}

async function discover(){V.innerHTML='<div class="discover-head"><h2>Discover</h2><div class="sub">Search for any show or movie.</div></div><div class="discover-search"><input id="q" class="search" placeholder="Search shows and movies" onkeydown="if(event.key===\'Enter\')searchShows()"><button aria-label="Search" onclick="searchShows()">⌕</button></div><button class="movies-browse-btn" onclick="movieDiscover()">🎬 Browse Upcoming Movies</button><div class="discover-title"><b>Discover</b><span>Search above or browse upcoming movies</span></div><div id="results" class="discover-results"><div class="discover-empty">Search for a show, movie, or actor.</div></div>'}

async function movieDiscover(){discoverReturnMode='movies';const R=$('#results');if(!R)return;R.innerHTML='<div class="discover-title"><b>Upcoming Movies</b><span>U.S. releases coming soon</span></div><div class="discover-empty">Loading upcoming movies…</div>';try{const d=await fetch(SUPABASE_URL+'/functions/v1/tmdb-search?mode=upcoming',{headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+SUPABASE_ANON}}).then(r=>{if(!r.ok)throw Error();return r.json()});const today=new Date().toISOString().slice(0,10),a=(d.results||[]).filter(x=>!x.release_date||x.release_date>=today);R.innerHTML='<div class="discover-title"><b>Upcoming Movies</b><span>U.S. releases coming soon</span></div><div class="movie-grid">'+a.map(x=>{const saved=movieWatchlist.some(y=>Number(y.id)===Number(x.id));return '<div class="movie-card">'+(x.poster?'<img src="'+esc(x.poster)+'" alt="">':'<div class="movie-no-poster">🎬</div>')+'<div class="movie-card-info"><b>'+esc(x.title)+'</b><span>'+esc(x.release_date?new Date(x.release_date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'Release date pending')+'</span><button class="btn" '+(saved?'disabled':'onclick="addMovieWatchlist('+Number(x.id)+',\''+encodeURIComponent(x.title)+'\',\''+encodeURIComponent(x.poster||'')+'\',\''+encodeURIComponent(x.release_date||'')+'\')"')+'>'+(saved?'✓ In Watchlist':'Add to Watchlist')+'</button><button class="movie-details" onclick="tmdbDetails('+Number(x.id)+',\'movie\')">Details</button></div></div>'}).join('')+'</div>'}catch{R.innerHTML='<div class="discover-empty">Upcoming movies are unavailable right now.</div>'}}async function addMovieWatchlist(id,title,poster,release_date){if(!(await hasPlan('plus'))){return lockedFeature('Movie Watchlist','Calendar+ or higher')}title=decodeURIComponent(title);poster=decodeURIComponent(poster);release_date=decodeURIComponent(release_date);if(!movieWatchlist.some(x=>Number(x.id)===Number(id))){movieWatchlist.push({id:Number(id),title,poster,release_date});save('mytv-v6-movie-watchlist',movieWatchlist);syncNotificationTitles()}alert('✓ '+title+' added to your movie watchlist.');movieDiscover()}
let discoverReturnMode='search';
function selectDiscoverChip(btn){document.querySelectorAll('.discover-chips button').forEach(b=>b.classList.remove('active'));if(btn)btn.classList.add('active')}function quickDiscover(q,btn){selectDiscoverChip(btn);const e=$('#q');if(e){e.value=q;searchShows()}}let discoverLastQuery='';
async function searchShows(qOverride){
 discoverReturnMode='search';
 const q=(typeof qOverride==='string'?qOverride:($('#q')?.value||'')).trim(),R=$('#results');if(!q||!R)return;discoverLastQuery=q;R.innerHTML='<div class="sub">Searching shows, movies and actors…</div>';
 try{
  const [tm,tv]=await Promise.all([
   fetch(SUPABASE_URL+'/functions/v1/tmdb-search?query='+encodeURIComponent(q),{headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+SUPABASE_ANON}}).then(r=>r.ok?r.json():({results:[]})),
   fetch('https://api.tvmaze.com/search/shows?q='+encodeURIComponent(q)).then(r=>r.json()).catch(()=>[])
  ]);
  const movie=(tm.results||[]).filter(x=>x.type==='movie').map(x=>'<div class="card discover-pick" onclick="tmdbDetails('+Number(x.id)+',\'movie\')"><div class="showrow">'+(x.poster?'<img class="poster" src="'+esc(x.poster)+'">':'<div></div>')+'<div><div class="title">🎬 '+esc(x.title)+'</div><div class="sub">'+esc((x.actor?'With '+x.actor+' • ':'')+(x.year||'')+' • Movie')+'</div><div class="sub">Movie information only • Tap for details →</div></div></div></div>').join('');
  const show=tv.slice(0,8).map(z=>{const x=z.show,on=shows.some(y=>Number(y.id)===Number(x.id));return '<div class="card"><div class="showrow">'+(x.image?.medium?'<img class="poster" src="'+esc(x.image.medium)+'">':'<div></div>')+'<div><div class="title">📺 '+esc(x.name)+'</div><div class="sub">'+esc(x.network?.name||x.webChannel?.name||x.status||'TV')+'</div></div><div class="actions single">'+(on?'<button class="btn" disabled>Following</button>':'<button class="btn" onclick="follow('+Number(x.id)+')">Save + Follow</button>')+'</div></div></div>'}).join('');
  R.innerHTML=movie+show||'<div class="empty">No results.</div>';
 }catch{R.innerHTML='<div class="empty">Search is unavailable right now.</div>'}
}
function returnToDiscoverResults(){if(discoverReturnMode==='movies'){movieDiscover();return}const q=discoverLastQuery;if(!q){discover();return}const input=$('#q');if(input)input.value=q;searchShows(q)}
async function tmdbDetails(id,type){const R=$('#results');if(!R)return;R.innerHTML='<div class="sub">Loading details…</div>';try{const r=await fetch(SUPABASE_URL+'/functions/v1/tmdb-search?id='+id+'&type='+encodeURIComponent(type),{headers:{apikey:SUPABASE_ANON,Authorization:'Bearer '+SUPABASE_ANON}});const d=await r.json(),x=d.detail;if(!x)throw Error();R.innerHTML='<button class="btn" onclick="returnToDiscoverResults()">← Back to results</button><div class="card" style="margin-top:12px">'+(x.poster?'<img class="poster" src="'+esc(x.poster)+'">':'')+'<div class="title" style="margin-top:10px">'+esc(x.title)+'</div><div class="sub">'+esc((x.year||'')+' • '+(type==='movie'?'Movie':'TV'))+'</div><div style="margin-top:10px">'+esc(x.overview||'No description available.')+'</div></div><h3>Where to Watch</h3><div id="tmdb-wtw" class="card"><div class="sub">Checking streaming availability…</div></div>';const W=$('#tmdb-wtw'),p=await realProviders(x.title,'movie',x.id);if(W)W.innerHTML=p?.providers?.length?p.providers.map(a=>'<div class="sub">'+esc(a.name||a.provider_name||'Provider')+'</div>').join(''):'<div class="empty">No verified U.S. streaming options found.</div>'}catch{R.innerHTML='<div class="empty">Details are unavailable right now.</div>'}}

async function follow(id){try{if(!(await hasPlan('plus'))&&shows.length>=5){lockedFeature('Unlimited Followed Shows','Calendar+ or higher');return}let x=await fetch('https://api.tvmaze.com/shows/'+id+'?embed=nextepisode').then(r=>{if(!r.ok)throw Error();return r.json()});let e=x._embedded?.nextepisode||{};let added=false;if(!shows.some(y=>Number(y.id)===Number(id))){shows.push({id:Number(x.id),name:x.name,network:x.network?.name||x.webChannel?.name||'',webChannel:!!x.webChannel,status:x.status,image:x.image?.medium||'',airdate:e.airdate||'',airtime:e.airtime||'',airstamp:e.airstamp||'',next_episode:e.name||''});save(K.shows,shows);syncNotificationTitles();added=true}alert(added?'✓ '+x.name+' has been added to My Shows.':x.name+' is already in My Shows.');if(route==='discover')await searchShows(discoverLastQuery)}catch{alert('The show could not be added right now. Please try again.')}}
function unfollow(id){shows=shows.filter(x=>Number(x.id)!==Number(id));save(K.shows,shows);syncNotificationTitles();myshows()}
async function details(id){
  let local=shows.find(x=>Number(x.id)===Number(id)),x=local;
  try{x=await fetch('https://api.tvmaze.com/shows/'+id).then(r=>{if(!r.ok)throw Error();return r.json()})}catch{}
  const name=x?.name||local?.name||'Show Details';
  V.innerHTML='<h2>'+esc(name)+'</h2><div class="card">'+(x?.image?.medium?'<img class="poster" src="'+esc(x.image.medium)+'">':'')+'<div class="sub" style="margin-top:12px">'+(x?.summary?x.summary.replace(/<[^>]+>/g,''):esc(local?.network||''))+'</div></div><h3>Where to Watch</h3><div id="wtw" class="card"><div class="sub">Checking verified U.S. streaming availability…</div></div><button class="btn" style="margin-top:14px" onclick="go(\''+route+'\')">Back</button>';
  const W=$('#wtw'),d=await realProviders(name);
  if(!W)return;
  if(!d){W.innerHTML='<div class="empty">Where to Watch is unavailable right now.</div>';return}
  if(!d.found||!d.providers?.length){W.innerHTML='<div class="empty">No verified U.S. streaming options were found for this show.</div>';return}
  const labels={flatrate:'Stream',free:'Free',ads:'With Ads',rent:'Rent',buy:'Buy'};
  W.innerHTML='<div class="sub" style="margin-bottom:10px">Verified provider availability for the U.S.</div>'+d.providers.map(p=>'<div style="display:flex;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid #e7edf5">'+(p.logo?'<img src="'+esc(p.logo)+'" alt="" style="width:38px;height:38px;border-radius:8px;object-fit:cover">':'')+'<div><b>'+esc(p.name)+'</b><div class="sub">'+esc(labels[p.type]||p.type)+'</div></div></div>').join('')+(d.link?'<a class="btn" style="display:inline-block;text-decoration:none;margin-top:12px" href="'+esc(d.link)+'" target="_blank" rel="noopener">View Watch Options</a>':'')
}
function more(){V.innerHTML='<h2>More</h2>'+[['catchup','Catch Up'],['night','Build My Night'],['subscriptions','Subscriptions'],['settings','Settings']].map(x=>'<button class="card" style="width:100%;text-align:left;font-weight:800" data-go="'+x[0]+'" onclick="go(\''+x[0]+'\')">'+x[1]+'</button>').join('')}
let catchupEpisodeCache=new Map();
async function catchup(){
 if(!(await hasPlan('plus'))){return lockedFeature('Catch Up','Calendar+ or higher')}
 V.innerHTML='<h2>Catch Up</h2><div class="sub" style="margin-bottom:16px">Your followed shows, organized by show and season. Open only the season you want.</div><div id="catchupList"><div class="empty">Loading episodes…</div></div>';
 const R=$('#catchupList');if(!shows.length){R.innerHTML='<div class="empty">Follow shows from Discover and they will appear here.</div>';return}
 const today=new Date();today.setHours(23,59,59,999);
 const results=await Promise.all(shows.map(async s=>{try{const eps=await fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'/episodes').then(r=>{if(!r.ok)throw Error();return r.json()});return{show:s,eps:eps.filter(e=>e.airdate&&new Date(e.airdate+'T23:59:59')<=today)}}catch{return{show:s,eps:[],error:true}}}));
 catchupEpisodeCache=new Map(results.filter(r=>!r.error).map(r=>[Number(r.show.id),r.eps]));
 R.innerHTML=results.map(({show,eps,error})=>{if(error)return '<div class="card"><div class="title">'+esc(show.name)+'</div><div class="sub">Episode data unavailable right now.</div></div>';if(!eps.length)return '';
 const seasons={};eps.forEach(e=>(seasons[e.season??0]||(seasons[e.season??0]=[])).push(e));
 const total=eps.length,completed=eps.filter(e=>watched[String(e.id)]).length,remaining=total-completed;const status=remaining===0?'All caught up':completed===0?'Not started':remaining+' to watch';
 const seasonButtons=Object.keys(seasons).sort((a,b)=>Number(b)-Number(a)).map(sn=>{const a=seasons[sn],done=a.filter(e=>watched[String(e.id)]).length,left=a.length-done;return '<div data-catchup-season="'+Number(sn)+'" style="display:flex;align-items:center;gap:8px;padding:8px 0"><button style="flex:1;min-width:0;text-align:left;border:0;background:transparent;color:inherit;padding:0;cursor:pointer" onclick="openCatchupSeason('+Number(show.id)+','+Number(sn)+')"><span style="font-weight:650;font-size:14px">Season '+sn+'</span><span data-season-status style="font-size:12px;opacity:.65;margin-left:8px">'+(left===0?'✓ Watched':left+' to watch')+'</span></button><div data-season-actions style="display:flex;gap:5px;flex-shrink:0">'+(left>0?'<button class="btn" style="font-size:10px;padding:5px 7px" onclick="watchAllSeason('+Number(show.id)+','+Number(sn)+')">Watch All</button>':'')+(done>0?'<button class="btn" style="font-size:10px;padding:5px 7px;background:transparent;color:inherit;border:1px solid #ccd5df" onclick="unwatchAllSeason('+Number(show.id)+','+Number(sn)+')">Unwatch All</button>':'')+'</div></div>'}).join('');
 return '<section class="card" data-catchup-show="'+Number(show.id)+'" style="padding:14px"><div style="display:flex;align-items:center;gap:12px">'+(show.image?'<img class="poster" style="width:54px;height:78px" src="'+esc(show.image)+'">':'')+'<div style="min-width:0"><div class="title">'+esc(show.name)+'</div><div class="sub" data-watch-summary style="margin-top:4px">'+status+' · '+completed+' of '+total+' watched</div></div></div><div style="margin-top:10px">'+seasonButtons+'</div></section>'}).join('')||'<div class="empty">No aired episodes found.</div>';
}
async function openCatchupSeason(showId,season){const s=shows.find(x=>Number(x.id)===Number(showId));V.innerHTML='<h2>'+esc(s?.name||'Catch Up')+'</h2><button class="btn" onclick="catchup()">← All Seasons</button><div id="catchupSeason" style="margin-top:12px"><div class="empty">Loading Season '+season+'…</div></div>';const R=$('#catchupSeason');try{const eps=await fetch('https://api.tvmaze.com/shows/'+Number(showId)+'/episodes').then(r=>r.json());const a=eps.filter(e=>Number(e.season)===Number(season)&&e.airdate&&new Date(e.airdate+'T23:59:59')<=new Date()).sort((x,y)=>Number(x.number)-Number(y.number));R.innerHTML='<div class="card"><div class="title">Season '+season+'</div><div class="sub">'+a.filter(e=>watched[String(e.id)]).length+' of '+a.length+' watched</div>'+(a.some(e=>!watched[String(e.id)])?'<button class="btn" style="margin-top:12px" onclick="watchAllSeason('+Number(showId)+','+Number(season)+')">✓ Watch All</button>':'')+(a.some(e=>watched[String(e.id)])?'<button class="btn" style="margin-top:12px;margin-left:8px" onclick="unwatchAllSeason('+Number(showId)+','+Number(season)+')">↶ Unwatch All</button>':'')+'</div>'+a.map(e=>{const done=!!watched[String(e.id)];return '<div class="card"><div class="title">Episode '+(e.number??'—')+' • '+esc(e.name||'Episode')+'</div><div class="sub">'+esc(mdY(e.airdate))+(e.runtime?' • '+e.runtime+' min':'')+'</div><button class="btn" style="margin-top:10px;'+(done?'background:#19a974':'')+'" onclick="toggleWatchedSeason('+Number(e.id)+','+Number(showId)+','+Number(season)+')">'+(done?'✓ Watched':'Mark Watched')+'</button></div>'}).join('')}catch{R.innerHTML='<div class="empty">Could not load this season right now.</div>'}}
async function watchAllCatchup(){if(!shows.length)return;try{const results=await Promise.all(shows.map(async s=>{const r=await fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'/episodes');if(!r.ok)throw Error('Episodes unavailable');return r.json()}));const now=new Date();const ids=[...new Set(results.flat().filter(e=>e.id&&e.airdate&&new Date(e.airdate+'T23:59:59')<=now&&!watched[String(e.id)]).map(e=>String(e.id)))];if(!ids.length){alert('All aired episodes are already marked Watched.');return}if(!confirm('Mark '+ids.length+' aired episodes across all followed shows as Watched? This will hide them from your calendar.'))return;ids.forEach(id=>watched[id]=true);save(K.watched,watched);catchup()}catch{alert('Could not load all episodes. No changes were made. Please try again.')}}
function updateCatchupShowInPlace(showId){const eps=catchupEpisodeCache.get(Number(showId));const card=document.querySelector('[data-catchup-show="'+Number(showId)+'"]');if(!eps||!card)return false;const total=eps.length,completed=eps.filter(e=>watched[String(e.id)]).length,remaining=total-completed;const summary=card.querySelector('[data-watch-summary]');if(summary)summary.textContent=(remaining===0?'All caught up':completed===0?'Not started':remaining+' to watch')+' · '+completed+' of '+total+' watched';card.querySelectorAll('[data-catchup-season]').forEach(row=>{const sn=Number(row.getAttribute('data-catchup-season'));const a=eps.filter(e=>Number(e.season??0)===sn),done=a.filter(e=>watched[String(e.id)]).length,left=a.length-done;const status=row.querySelector('[data-season-status]');if(status)status.textContent=left===0?'✓ Watched':left+' to watch';const actions=row.querySelector('[data-season-actions]');if(actions)actions.innerHTML=(left>0?'<button class="btn" style="font-size:10px;padding:5px 7px" onclick="watchAllSeason('+Number(showId)+','+sn+')">Watch All</button>':'')+(done>0?'<button class="btn" style="font-size:10px;padding:5px 7px;background:transparent;color:inherit;border:1px solid #ccd5df" onclick="unwatchAllSeason('+Number(showId)+','+sn+')">Unwatch All</button>':'')});return true}
async function refreshWatchedWithoutJump(showId,season){const inSeason=!!document.getElementById('catchupSeason');const pageY=window.scrollY,viewY=V.scrollTop;const scroller=document.scrollingElement,scrollY=scroller?scroller.scrollTop:pageY;if(inSeason)await openCatchupSeason(showId,season);else if(!updateCatchupShowInPlace(showId))await catchup();requestAnimationFrame(()=>{if(scroller)scroller.scrollTop=scrollY;window.scrollTo(0,pageY);V.scrollTop=viewY;requestAnimationFrame(()=>{if(scroller)scroller.scrollTop=scrollY;window.scrollTo(0,pageY);V.scrollTop=viewY})})}
async function setSeasonWatched(showId,season,mark){try{const show=Number(showId),sn=Number(season);let eps=catchupEpisodeCache.get(show);if(!eps){const response=await fetch('https://api.tvmaze.com/shows/'+show+'/episodes');if(!response.ok)throw Error('Episode list unavailable');const all=await response.json();const today=new Date();today.setHours(23,59,59,999);eps=all.filter(e=>e.airdate&&new Date(e.airdate+'T23:59:59')<=today)}const ids=eps.filter(e=>Number(e.season??0)===sn&&e.id&&Boolean(watched[String(e.id)])!==mark).map(e=>String(e.id));if(!ids.length){await refreshWatchedWithoutJump(show,sn);return}if(!confirm((mark?'Mark all '+ids.length+' remaining episodes':'Mark '+ids.length+' watched episodes')+' in Season '+sn+' as '+(mark?'Watched':'Unwatched')+'?'))return;ids.forEach(id=>{if(mark)watched[id]=true;else delete watched[id]});save(K.watched,watched);await refreshWatchedWithoutJump(show,sn)}catch(err){alert('Could not update this season. Please try again.')}}
async function watchAllSeason(showId,season){return setSeasonWatched(showId,season,true)}
async function unwatchAllSeason(showId,season){return setSeasonWatched(showId,season,false)}
function toggleWatchedSeason(id,showId,season){const k=String(id);if(watched[k])delete watched[k];else watched[k]=true;save(K.watched,watched);openCatchupSeason(showId,season)}
function toggleWatched(id){const k=String(id);if(watched[k])delete watched[k];else watched[k]=true;save(K.watched,watched);catchup()}
let nightLastPlan=[];
async function night(){if(!(await hasPlan('pro'))){return lockedFeature('Build My Night','Pro or Lifetime')}V.innerHTML='<h2>Build My Night</h2><div class="sub" style="margin-bottom:16px">Create a personalized lineup from your shows and movie watchlist.</div><div class="card"><div class="title">1. Time</div><select id="nightBudget" class="search"><option value="30">30 mins</option><option value="60">1 hour</option><option value="90">1.5 hours</option><option value="120" selected>2 hours</option><option value="180">3 hours</option><option value="240">4 hours</option></select></div><div class="card"><div class="title">2. What are you in the mood for?</div><select id="nightMood" class="search"><option value="any">Anything</option><option>Comedy</option><option>Drama</option><option>Action</option><option>Crime</option><option>Reality</option></select></div><div class="card"><div class="title">3. What should I use?</div><select id="nightSource" class="search"><option value="shows">My TV Shows</option><option value="favorites">Favorites First</option><option value="mix">TV Shows + Movie Watchlist</option></select></div><div class="card"><div class="title">4. Who is watching?</div><select id="nightGroup" class="search"><option>Just Me</option><option>Couple / Date Night</option><option>Family</option><option>Friends</option></select></div><div class="card"><div class="title">5. Plan style</div><select id="nightStyle" class="search"><option value="catchup">Catch Up</option><option value="favorites">Favorites First</option><option value="different">Something Different</option><option value="surprise">Surprise Me</option></select><button class="btn" style="width:100%;margin-top:14px" onclick="buildNight()">Build My Night</button></div><div id="nightPlan"></div>'}
async function buildNight(){const R=$('#nightPlan'),budget=Number($('#nightBudget')?.value||120),style=$('#nightStyle')?.value||'catchup';R.innerHTML='<div class="empty">Building your night…</div>';const today=new Date();today.setHours(23,59,59,999);let all=[];await Promise.all(shows.map(async s=>{try{const eps=await fetch('https://api.tvmaze.com/shows/'+Number(s.id)+'/episodes').then(r=>r.json());eps.forEach(e=>{if(e.airdate&&new Date(e.airdate+'T23:59:59')<=today&&!watched[String(e.id)])all.push({show:s,e,mins:Number(e.runtime||s.runtime||45),fav:!!favorites[String(s.id)]})})}catch{}}));if(style==='favorites')all.sort((a,b)=>Number(b.fav)-Number(a.fav));else if(style==='different')all.sort((a,b)=>String(a.show.name).localeCompare(String(b.show.name)));else if(style==='surprise')all.sort(()=>Math.random()-.5);else all.sort((a,b)=>String(b.e.airdate).localeCompare(String(a.e.airdate)));let left=budget,plan=[];for(const x of all){if(x.mins<=left){plan.push(x);left-=x.mins}}nightLastPlan=plan;if(!plan.length){R.innerHTML='<div class="empty">No unwatched episodes fit this plan. Try more time or another style.</div>';return}R.innerHTML='<div class="card"><div class="title">Your '+budget+'-Minute Night Is Ready</div><div class="sub">'+(budget-left)+' minutes planned • '+left+' minutes free</div><button class="btn" style="margin-top:10px" onclick="buildNight()">↻ Shuffle / Rebuild</button></div>'+plan.map((x,i)=>'<div class="card"><div class="sub">#'+(i+1)+' • '+x.mins+' min</div><div class="title">'+esc(x.show.name)+'</div><div>'+esc('S'+String(x.e.season??0).padStart(2,'0')+'E'+String(x.e.number??0).padStart(2,'0')+' • '+(x.e.name||'Episode'))+'</div><button class="btn" style="margin-top:10px" onclick="nightWatched('+Number(x.e.id)+')">✓ Mark Watched</button></div>').join('')}
function nightWatched(id){watched[String(id)]=true;save(K.watched,watched);buildNight()}
function notificationPrefs(){return load('mytv-notification-prefs',{showToday:true,movieToday:true,showSoon:false,dateChanges:false,newSeason:false,appUpdates:false})}
function setNotificationPref(k,v){const p=notificationPrefs();p[k]=!!v;save('mytv-notification-prefs',p);syncNotificationPrefs()}
async function settings(){
 const plan=await getCurrentPlan(),level=PLAN_LEVELS[plan]||0,p=notificationPrefs();
 const row=(k,label,desc,need=0,badge='Free')=>{const locked=level<need;return '<label class="card" style="display:flex;align-items:center;justify-content:space-between;gap:14px;'+(locked?'opacity:.5;':'')+'"><div><div class="title">'+label+(locked?' <span class="sub">• '+badge+'</span>':'')+'</div><div class="sub">'+desc+'</div></div><input type="checkbox" '+(!locked&&p[k]?'checked':'')+' '+(locked?'disabled':'onchange="setNotificationPref(\''+k+'\',this.checked)"')+' style="width:22px;height:22px;flex:0 0 auto"></label>'};
 V.innerHTML='<h2>Settings</h2><div class="card"><div class="title">Push Notifications</div><div class="sub">Enable notifications, then choose the reminders included with your plan.</div><button type="button" id="push-toggle" class="btn" data-push="on" style="margin-top:12px">Enable Push Notifications</button><div id="push-msg" class="sub" style="margin-top:10px"></div></div><div class="title" style="margin:18px 0 10px">Notification Preferences</div>'+row('showToday','📺 Show Airing Today','Remind me when a followed show has a new episode today.',0,'Free')+row('movieToday','🎬 Movie Release Today','Remind me when a movie in my Watchlist releases today.',1,'Calendar+')+row('dateChanges','📅 Release Date Changes','Tell me when a followed show or movie release date changes.',1,'Calendar+')+row('showSoon','⏰ Show Starting Soon','Remind me shortly before a followed show starts.',2,'Pro')+row('newSeason','✨ New Season / Premiere','Tell me when a followed show begins a new season.',2,'Pro')+row('appUpdates','🔔 My TV Calendar Updates','Important app and account announcements.',0,'Free')+'<div class="card">My TV Calendar V6.4.78</div>';
 renderPushButton();
}
const BILLING_PORTAL='https://billing.stripe.com/p/login/8x24gycwP7vC7kT1Aeco000';
const PAYMENT_LINKS={plus:'https://buy.stripe.com/dRm7sKfJ17vC9t17YCco003',pro:'https://buy.stripe.com/5kQ8wO1Sb8zG8oXfr4co004',lifetime:'https://buy.stripe.com/8x2fZgeEX6rygVt5Quco005'};
const PLAN_LABELS={free:'Free',plus:'Calendar+',pro:'Pro',lifetime:'Lifetime'};
const PLAN_LEVELS={free:0,plus:1,pro:2,lifetime:3};
let PLAN_CACHE={plan:'free',at:0};
async function getSessionUser(){if(!SB)return null;try{const {data}=await SB.auth.getSession();return data?.session?.user||null}catch{return null}}
async function getCurrentPlan(force=false){
 if(!force&&Date.now()-PLAN_CACHE.at<15000)return PLAN_CACHE.plan;
 const user=await getSessionUser();if(!user){PLAN_CACHE={plan:'free',at:Date.now()};return'free'}
 try{
  const {data,error}=await SB.from('user_entitlements').select('plan,status,lifetime,current_period_end,updated_at').order('updated_at',{ascending:false});
  if(error)throw error;
  const good=(data||[]).filter(x=>x.lifetime||['active','trialing'].includes(String(x.status||'')));
  const plan=good.reduce((best,x)=>(PLAN_LEVELS[x.plan]||0)>(PLAN_LEVELS[best]||0)?x.plan:best,'free');
  PLAN_CACHE={plan,at:Date.now()};return plan;
 }catch{PLAN_CACHE={plan:'free',at:Date.now()};return'free'}
}
async function hasPlan(required){const user=await getSessionUser();if(!user){PLAN_CACHE={plan:'free',at:Date.now()};return false}const p=await getCurrentPlan(true);return (PLAN_LEVELS[p]||0)>=(PLAN_LEVELS[required]||0)}
function lockedFeature(name,need){V.innerHTML='<h2>'+esc(name)+'</h2><div class="card"><div class="title">Premium Feature</div><div class="sub">'+esc(name)+' is available with '+esc(need)+'.</div><button class="btn" style="width:100%;margin-top:14px" onclick="go(\'subscriptions\')">View Subscriptions</button></div>'}
async function subscriptions(){
 const user=await getSessionUser();
 const plan=await getCurrentPlan(true);
 const paidSuccess=new URLSearchParams(location.search).get('payment')==='success';
 const notice=paidSuccess?'<div class="card" style="border:2px solid #19a974"><div class="title">Payment received</div><div class="sub">Stripe is confirming your purchase. Your plan updates automatically.</div></div>':'';
 const account=user?'<div class="card"><div class="title">Account</div><div class="sub">'+esc(user.email||'Signed in')+'</div><div style="margin-top:10px"><b>Current plan: '+esc(PLAN_LABELS[plan]||'Free')+'</b></div>'+(plan!=='free'?'<a class="btn" style="display:inline-block;text-decoration:none;margin-top:12px" href="'+BILLING_PORTAL+'" target="_blank" rel="noopener">Manage Billing</a>':'')+'<button class="btn" style="margin-top:12px;margin-left:8px" onclick="signOutAccount()">Sign Out</button></div>':'<div class="card"><div class="title">Sign in to subscribe</div><div class="sub">Use the same account for checkout so paid access activates automatically.</div><input id="subEmail" class="search" type="email" placeholder="Email" style="margin-top:12px"><input id="subPass" class="search" type="text" placeholder="Password" autocomplete="off" style="margin-top:8px;width:100%;box-sizing:border-box"><div style="display:flex;gap:8px;margin-top:10px"><button class="btn" style="flex:1" onclick="signInAccount()">Sign In</button><button class="btn" style="flex:1" onclick="createAccount()">Create Account</button></div><div id="subAuthMsg" class="sub" style="margin-top:10px"></div></div>';
 const disabled=user?'':'disabled style="width:100%;margin-top:14px;opacity:.55"';
 const enabledStyle='style="width:100%;margin-top:14px"';
 const owns=t=>(PLAN_LEVELS[plan]||0)>=(PLAN_LEVELS[t]||0);
 V.innerHTML='<h2>Subscriptions</h2><div class="sub" style="margin-bottom:16px">Choose the plan that fits how you watch.</div>'+notice+account+
 '<div class="card"><div class="title">Free</div><h2 style="margin:6px 0">$0</h2><div class="sub">My Calendar • My Shows • Discover • Follow up to 5 shows • Show Airing Today notifications • My TV Calendar updates</div></div>'+
 '<div class="card" style="border:2px solid #e53935"><div class="sub">MOST POPULAR</div><div class="title">My TV Calendar+</div><h2 style="margin:6px 0">$2.99 <span class="sub">/ month</span></h2><div class="sub">Catch Up • Movie Watchlist • Unlimited followed shows • Movie Release Today alerts • Release Date Change alerts</div><button class="btn" '+(owns('plus')?'disabled style="width:100%;margin-top:14px;opacity:.65"':(user?enabledStyle:disabled))+' onclick="startCheckout(\'plus\')">'+(owns('plus')?'Included in '+esc(PLAN_LABELS[plan]):'Upgrade to Calendar+')+'</button></div>'+
 '<div class="card"><div class="title">My TV Calendar Pro</div><h2 style="margin:6px 0">$4.99 <span class="sub">/ month</span></h2><div class="sub">Everything in Calendar+ • Build My Night • Show Starting Soon alerts • New Season / Premiere alerts • Advanced planning features</div><button class="btn" '+(owns('pro')?'disabled style="width:100%;margin-top:14px;opacity:.65"':(user?enabledStyle:disabled))+' onclick="startCheckout(\'pro\')">'+(owns('pro')?'Included in '+esc(PLAN_LABELS[plan]):'Go Pro')+'</button></div>'+
 '<div class="card"><div class="title">My TV Calendar Lifetime</div><h2 style="margin:6px 0">$29.99 <span class="sub">one time</span></h2><div class="sub">Pay once and unlock all current premium features and all notification types with no monthly subscription.</div><button class="btn" '+(plan==='lifetime'?'disabled style="width:100%;margin-top:14px;opacity:.65"':(user?enabledStyle:disabled))+' onclick="startCheckout(\'lifetime\')">'+(plan==='lifetime'?'Current Plan':'Get Lifetime Access')+'</button></div>'+
 '<div class="sub" style="text-align:center;margin:14px">Secure checkout powered by Stripe.</div>';
 if(paidSuccess&&history.replaceState){const u=new URL(location.href);u.searchParams.delete('payment');history.replaceState({},'',u.toString())}
}
function showAccountCreatedModal(email,needsConfirm=true,existing=false){
 const old=document.getElementById('accountCreatedModal');if(old)old.remove();
 const d=document.createElement('div');d.id='accountCreatedModal';d.style.cssText='position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.72);display:flex;align-items:center;justify-content:center;padding:22px';
 const msg=!needsConfirm?'Your account is ready and you are signed in.':existing?'This email already has an account. If you still need to confirm it, tap Resend Confirmation Email below.':'We sent a confirmation email to <b>'+esc(email)+'</b>. Open the email and tap the confirmation link before signing in.';
 const resend=needsConfirm?'<button class="btn" style="width:100%;margin-top:10px" onclick="resendConfirmation(\''+String(email).replace(/'/g,"\\'")+'\')">Resend Confirmation Email</button>':'';
 d.innerHTML='<div class="card" style="width:min(420px,100%);text-align:center;padding:24px"><div style="font-size:42px;margin-bottom:8px">✓</div><div class="title" style="font-size:22px">'+(existing?'Account Already Exists':'Account Created')+'</div><div id="accountConfirmMsg" class="sub" style="margin-top:10px">'+msg+'</div>'+resend+'<button class="btn" style="width:100%;margin-top:10px" onclick="closeAccountCreatedModal()">OK</button></div>';
 document.body.appendChild(d);
}
async function resendConfirmation(email){
 const m=$('#accountConfirmMsg');if(m)m.textContent='Sending confirmation email…';
 try{const {error}=await SB.auth.resend({type:'signup',email,options:{emailRedirectTo:'https://animaxionx.github.io/mytv-calendar/?route=subscriptions'}});if(error)throw error;if(m)m.textContent='Confirmation email sent. Check your inbox and spam folder.'}
 catch(err){if(m)m.textContent='Could not resend confirmation email. '+(err?.message||'Please try again.')}
}
function closeAccountCreatedModal(){document.getElementById('accountCreatedModal')?.remove();subscriptions()}
function togglePasswordVisibility(){const p=$('#subPass'),b=$('#pwToggle');if(!p||!b)return;const hidden=p.getAttribute('data-password-state')!=='visible';if(hidden){p.type='text';p.setAttribute('data-password-state','visible');b.textContent='◉';b.title='Hide password';b.setAttribute('aria-label','Hide password')}else{p.type='password';p.setAttribute('data-password-state','hidden');b.textContent='👁';b.title='Show password';b.setAttribute('aria-label','Show password')}}
async function signInAccount(){
 const e=$('#subEmail')?.value.trim(),p=$('#subPass')?.value||'',m=$('#subAuthMsg'),b=document.querySelector('button[onclick="signInAccount()"]');
 if(!e||!p){if(m)m.textContent='Enter your email and password.';return}
 if(!SB){if(m)m.textContent='Login service did not load. Refresh the app and try again.';return}
 if(m)m.textContent='Signing in…';if(b){b.disabled=true;b.textContent='Signing In…'}
 try{
  const {data,error}=await SB.auth.signInWithPassword({email:e,password:p});
  if(error){if(m)m.textContent=error.message;return}
  if(!data?.session){if(m)m.textContent='Sign in was not completed. Check your email confirmation and try again.';return}
  PLAN_CACHE.at=0;if(m)m.textContent='Signed in successfully.';await getCurrentPlan(true);await reconcileNotificationRegistration();await go('home');
 }catch(err){if(m)m.textContent='Could not sign in. '+(err?.message||'Please try again.')}
 finally{if(b){b.disabled=false;b.textContent='Sign In'}}
}
async function createAccount(){
 const e=$('#subEmail')?.value.trim(),p=$('#subPass')?.value||'',m=$('#subAuthMsg'),b=document.querySelector('button[onclick="createAccount()"]');
 if(!e||p.length<6){if(m)m.textContent='Enter a valid email and a password with at least 6 characters.';return}
 if(!SB){if(m)m.textContent='Account service did not load. Refresh the app and try again.';return}
 if(m)m.textContent='Creating account…';if(b){b.disabled=true;b.textContent='Creating…'}
 try{
  const {data,error}=await SB.auth.signUp({email:e,password:p,options:{emailRedirectTo:'https://animaxionx.github.io/mytv-calendar/?route=subscriptions'}});
  if(error){if(m)m.textContent=error.message;return}
  if(data?.session){PLAN_CACHE.at=0;showAccountCreatedModal(e,false,false)}
  else {
   const created=String(data?.user?.identities?.length||0)!=='0';
   showAccountCreatedModal(e,true,!created);
  }
 }catch(err){if(m)m.textContent='Could not create account. '+(err?.message||'Please try again.')}
 finally{if(b){b.disabled=false;b.textContent='Create Account'}}
}
function passwordRecoveryScreen(){
 V.innerHTML='<h2>Reset Password</h2><div class="card"><div class="title">Create a new password</div><div class="sub">Enter your new password below.</div><input id="recoveryPass" class="search" type="password" placeholder="New Password" autocomplete="new-password" style="margin-top:12px"><input id="recoveryPass2" class="search" type="password" placeholder="Confirm New Password" autocomplete="new-password" style="margin-top:8px"><button id="recoveryBtn" class="btn" style="width:100%;margin-top:12px" onclick="completePasswordRecovery()">Update Password</button><div id="recoveryMsg" class="sub" style="margin-top:10px"></div></div>';
}
async function completePasswordRecovery(){
 const p=$('#recoveryPass')?.value||'',p2=$('#recoveryPass2')?.value||'',m=$('#recoveryMsg'),b=$('#recoveryBtn');
 if(p.length<6){if(m)m.textContent='Password must be at least 6 characters.';return}
 if(p!==p2){if(m)m.textContent='Passwords do not match.';return}
 if(m)m.textContent='Updating password…';if(b)b.disabled=true;
 try{const {error}=await SB.auth.updateUser({password:p});if(error)throw error;if(m)m.textContent='Password updated successfully. Taking you to your account…';PLAN_CACHE.at=0;setTimeout(()=>{go('subscriptions')},900)}
 catch(err){if(m)m.textContent='Could not update password. '+(err?.message||'Please request a new reset link and try again.')}
 finally{if(b)b.disabled=false}
}
async function signOutAccount(){if(SB)await SB.auth.signOut();PLAN_CACHE={plan:'free',at:Date.now()};await go('subscriptions')}
async function startCheckout(plan){
 const user=await getSessionUser();if(!user){alert('Sign in first so your purchase can activate automatically.');return}
 const base=PAYMENT_LINKS[plan];if(!base)return;
 const u=new URL(base);u.searchParams.set('locked_prefilled_email',user.email||'');u.searchParams.set('client_reference_id',user.id);location.href=u.toString();
}
const qs=new URLSearchParams(location.search);
let recoveryMode=false;
if(SB)SB.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recoveryMode=true;passwordRecoveryScreen()}});
(async()=>{if(SB){try{const {data}=await SB.auth.getSession();const h=new URLSearchParams(location.hash.replace(/^#/,''));if((h.get('type')==='recovery'||qs.get('type')==='recovery')&&data?.session){recoveryMode=true;passwordRecoveryScreen();return}}catch{}}
if(!recoveryMode){await reconcileNotificationRegistration();await refreshFollowedSchedules();if(qs.get('payment')==='success'||qs.get('route')==='subscriptions')await go('subscriptions');else await go('home')}})();